name: Android CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        run: echo "$KEYSTORE_BASE64" | base64 -d > app/corestudio.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Build Release AAB
        run: ./gradlew bundleRelease

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: Corestudio-APK
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Release AAB
        uses: actions/upload-artifact@v4
        with:
          name: Corestudio-AAB
          path: app/build/outputs/bundle/release/app-release.aab
