name: Android CI/CD

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode Keystore
        run: echo "$BASE64_KEYSTORE" | base64 -d > app/corestudio.jks
        env:
          BASE64_KEYSTORE: ${{ secrets.BASE64_KEYSTORE }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: CorestudioApp
          path: app/build/outputs/apk/release/*.apk
